### PR TITLE
Custom daily note format setting

### PR DESCRIPTION
**Pull request by Vladikasik**
Now anyone can change daily note filter for tasks by simply writing
For example

```
dailyNoteFormatString: "DD.MM.YY"
dailyNoteRegexString: "/d{2}\.\d{2}\.\d{2}/"
```

so final Dataview would look like

```dataviewjs
await dv.view("tasksCalendar", {pages: "", view: "month", firstDayOfWeek: 1, options: "style1", dailyNoteFolder: "Daily", dailyNoteFormatString: "DD.MM.YY", dailyNoteRegexString: "/d{2}\.\d{2}\.\d{2}/"})```

### CODE REVIEW

**Comment by Vladikasik** [comment]
Linking with daily notes means you can click on dates to open correct daily notes from calendar

**Comment by 702573N** [comment]
Thanks for you commit. I have already taken a similar approach. However, it bothers me that the user has to provide both information (regex string and moment.js format). The normal user can of course define a date format in moment.js format, but with regex it becomes more difficult for many users. I would like to pursue an approach that gets by with one parameter in moment.js format and can therefore also be used by normal users. So how can we get a regex string based on a moment.js format in an easy way?

**Comment by Vladikasik** [comment]
I am not a js programmer, but I think i can try to make it work. Can't say anything about dates, maybe in a week it could me done

**Comment by 702573N** [comment]
Please check the latest release [1.3.4](https://github.com/702573N/Obsidian-Tasks-Calendar/releases/tag/1.3.4)

**Pull request closed without merging**
